# Downloading CAISO Oasis Datasets

Grid Status provides access to many CAISO OASIS datasets. If one is missing, please post an issue on GitHub and we will add it

In [1]:
import gridstatus

iso = gridstatus.CAISO()
# autoreload
%load_ext autoreload
%autoreload 2

List All Available Oasis Datasets

In [2]:
iso.list_oasis_datasets()

Dataset: transmission_interface_usage
+---------------+-----------+-------------------+
| Parameter     | Default   | Possible Values   |
+===============+===========+===================+
| market_run_id | DAM       | DAM, HASP, RRPD   |
+---------------+-----------+-------------------+
| ti_id         | ALL       | N/A               |
+---------------+-----------+-------------------+
| ti_direction  | ALL       | ALL, E, I         |
+---------------+-----------+-------------------+


Dataset: schedule_by_tie
+-------------+------------------------+-------------------------------------------------------------------------------------------------+
| Parameter   | Default                | Possible Values                                                                                 |
+=============+========================+=================================================================================================+
| groupid     | RTD_ENE_SCH_BY_TIE_GRP | RTD_ENE_SCH_BY_TIE_GRP, DAM_ENE_SCH_BY_TIE_GRP, RUC_ENE_SCH_BY_TIE_GRP, RTPD_ENE_SCH_BY_TIE_GRP |
+-------------+------------------------+-------------------------------------------------------------------------------------------------+


Dataset: as_requirements
+---------------+-----------+---------------------+
| Parameter     | Default   | Possible Values     |
+===============+===========+=====================+
| market_run_id | DAM       | DAM, HASP, RTM, 2DA |
+---------------+-----------+---------------------+
| anc_type      | ALL       | N/A                 |
+---------------+-----------+---------------------+
| anc_region    | ALL       | N/A                 |
+---------------+-----------+---------------------+


Dataset: as_clearing_prices
+---------------+-----------+-------------------------------------------------------------------------+
| Parameter     | Default   | Possible Values                                                         |
+===============+===========+=========================================================================+
| market_run_id | DAM       | DAM, HASP                                                               |
+---------------+-----------+-------------------------------------------------------------------------+
| anc_type      | ALL       | ALL, NR, RD, RMD, RMU, RU, SR                                           |
+---------------+-----------+-------------------------------------------------------------------------+
| anc_region    | ALL       | ALL, AS_CAISO, AS_SP26_EXP, AS_SP26, AS_CAISO_EXP, AS_NP26_EXP, AS_NP26 |
+---------------+-----------+-------------------------------------------------------------------------+


Dataset: fuel_prices
+----------------+-----------+-------------------+
| Parameter      | Default   | Possible Values   |
+================+===========+===================+
| fuel_region_id | ALL       | N/A               |
+----------------+-----------+-------------------+


Dataset: ghg_allowances
    No parameters


Dataset: wind_and_solar_forecast
    No parameters

Get Data for specific dataset and set of parameters

In [7]:
iso.list_oasis_datasets("as_clearing_prices")

Dataset: as_clearing_prices
+---------------+-----------+-------------------------------------------------------------------------+
| Parameter     | Default   | Possible Values                                                         |
+===============+===========+=========================================================================+
| market_run_id | DAM       | DAM, HASP                                                               |
+---------------+-----------+-------------------------------------------------------------------------+
| anc_type      | ALL       | ALL, NR, RD, RMD, RMU, RU, SR                                           |
+---------------+-----------+-------------------------------------------------------------------------+
| anc_region    | ALL       | ALL, AS_CAISO, AS_SP26_EXP, AS_SP26, AS_CAISO_EXP, AS_NP26_EXP, AS_NP26 |
+---------------+-----------+-------------------------------------------------------------------------+

In [4]:
df = iso.get_oasis_dataset(
    dataset="as_clearing_prices",
    params={
        "market_run_id": "DAM",
        "anc_type": "RMU",
        "anc_region": "AS_CAISO_EXP",
    },
    date="today",
)
df

,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,OPR_DT,OPR_HR,OPR_INTERVAL,OPR_TYPE,ANC_TYPE,ANC_REGION,MARKET_RUN_ID,XML_DATA_ITEM,MW,GROUP
0,2023-04-21T13:00:00-00:00,2023-04-21T14:00:00-00:00,2023-04-21,7,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
1,2023-04-22T05:00:00-00:00,2023-04-22T06:00:00-00:00,2023-04-21,23,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
2,2023-04-22T04:00:00-00:00,2023-04-22T05:00:00-00:00,2023-04-21,22,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
3,2023-04-21T08:00:00-00:00,2023-04-21T09:00:00-00:00,2023-04-21,2,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
4,2023-04-21T23:00:00-00:00,2023-04-22T00:00:00-00:00,2023-04-21,17,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
5,2023-04-22T02:00:00-00:00,2023-04-22T03:00:00-00:00,2023-04-21,20,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
6,2023-04-21T18:00:00-00:00,2023-04-21T19:00:00-00:00,2023-04-21,12,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
7,2023-04-22T03:00:00-00:00,2023-04-22T04:00:00-00:00,2023-04-21,21,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
8,2023-04-21T11:00:00-00:00,2023-04-21T12:00:00-00:00,2023-04-21,5,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
9,2023-04-21T16:00:00-00:00,2023-04-21T17:00:00-00:00,2023-04-21,10,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
10,2023-04-22T06:00:00-00:00,2023-04-22T07:00:00-00:00,2023-04-21,24,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
11,2023-04-21T10:00:00-00:00,2023-04-21T11:00:00-00:00,2023-04-21,4,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
12,2023-04-21T12:00:00-00:00,2023-04-21T13:00:00-00:00,2023-04-21,6,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
13,2023-04-21T14:00:00-00:00,2023-04-21T15:00:00-00:00,2023-04-21,8,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
14,2023-04-21T15:00:00-00:00,2023-04-21T16:00:00-00:00,2023-04-21,9,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
15,2023-04-21T22:00:00-00:00,2023-04-21T23:00:00-00:00,2023-04-21,16,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
16,2023-04-21T19:00:00-00:00,2023-04-21T20:00:00-00:00,2023-04-21,13,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
17,2023-04-22T00:00:00-00:00,2023-04-22T01:00:00-00:00,2023-04-21,18,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
18,2023-04-22T01:00:00-00:00,2023-04-22T02:00:00-00:00,2023-04-21,19,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
19,2023-04-21T07:00:00-00:00,2023-04-21T08:00:00-00:00,2023-04-21,1,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
20,2023-04-21T09:00:00-00:00,2023-04-21T10:00:00-00:00,2023-04-21,3,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
21,2023-04-21T17:00:00-00:00,2023-04-21T18:00:00-00:00,2023-04-21,11,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
22,2023-04-21T20:00:00-00:00,2023-04-21T21:00:00-00:00,2023-04-21,14,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1
23,2023-04-21T21:00:00-00:00,2023-04-21T22:00:00-00:00,2023-04-21,15,0,Hourly,RMU,AS_CAISO_EXP,DAM,RMU_CLR_PRC,0,1

Query for Date Range

In [8]:
iso.list_oasis_datasets("as_requirements")

Dataset: as_requirements
+---------------+-----------+---------------------+
| Parameter     | Default   | Possible Values     |
+===============+===========+=====================+
| market_run_id | DAM       | DAM, HASP, RTM, 2DA |
+---------------+-----------+---------------------+
| anc_type      | ALL       | N/A                 |
+---------------+-----------+---------------------+
| anc_region    | ALL       | N/A                 |
+---------------+-----------+---------------------+

In [12]:
df = iso.get_oasis_dataset(
    dataset="as_requirements",
    params={
        "market_run_id": "DAM",
    },
    start="2023-04-01",
    end="2023-04-21",
)
df

,POS,MARKET_RUN_ID,ANC_TYPE,ANC_REGION,LABEL,XML_DATA_ITEM,MW,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,OPR_DT,OPR_HR,OPR_INTERVAL,GROUP
0,5,DAM,NR,AS_CAISO,AS Regional AS Requirement Maximum,NS_REQ_MAX_MW,0.00,2023-04-01T21:00:00-00:00,2023-04-01T22:00:00-00:00,2023-04-01,15,0,1
1,5,DAM,NR,AS_CAISO,AS Regional AS Requirement Maximum,NS_REQ_MAX_MW,0.00,2023-04-01T09:00:00-00:00,2023-04-01T10:00:00-00:00,2023-04-01,3,0,1
2,5,DAM,NR,AS_CAISO,AS Regional AS Requirement Maximum,NS_REQ_MAX_MW,0.00,2023-04-01T16:00:00-00:00,2023-04-01T17:00:00-00:00,2023-04-01,10,0,1
3,5,DAM,NR,AS_CAISO,AS Regional AS Requirement Maximum,NS_REQ_MAX_MW,0.00,2023-04-01T10:00:00-00:00,2023-04-01T11:00:00-00:00,2023-04-01,4,0,1
4,5,DAM,NR,AS_CAISO,AS Regional AS Requirement Maximum,NS_REQ_MAX_MW,0.00,2023-04-02T02:00:00-00:00,2023-04-02T03:00:00-00:00,2023-04-01,20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24955,4,DAM,SR,AS_SP26_EXP,AS Regional AS Requirement Minimum,SP_REQ_MIN_MW,93.54,2023-04-20T07:00:00-00:00,2023-04-20T08:00:00-00:00,2023-04-20,1,0,1040
24956,4,DAM,SR,AS_SP26_EXP,AS Regional AS Requirement Minimum,SP_REQ_MIN_MW,143.19,2023-04-20T18:00:00-00:00,2023-04-20T19:00:00-00:00,2023-04-20,12,0,1040
24957,4,DAM,SR,AS_SP26_EXP,AS Regional AS Requirement Minimum,SP_REQ_MIN_MW,102.52,2023-04-21T05:00:00-00:00,2023-04-21T06:00:00-00:00,2023-04-20,23,0,1040
24958,4,DAM,SR,AS_SP26_EXP,AS Regional AS Requirement Minimum,SP_REQ_MIN_MW,123.88,2023-04-20T23:00:00-00:00,2023-04-21T00:00:00-00:00,2023-04-20,17,0,1040
24959,4,DAM,SR,AS_SP26_EXP,AS Regional AS Requirement Minimum,SP_REQ_MIN_MW,103.25,2023-04-20T14:00:00-00:00,2023-04-20T15:00:00-00:00,2023-04-20,8,0,1040